version: "2.2"

services:
  api:
    build:
      context: './rust-api'
    container_name: 'api'
    ports:
      - 3000:3000
    environment:
      ADDR: '0.0.0.0:3000'
      SERIAL_PORT: '/dev/ttyACM0'
      TZ: 'Europe/Brussels'
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - "./db.db3:/db.db3"
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 5s
      timeout: 2s
      retries: 5

  website:
    build:
      context: './nextjs-frontend'
    container_name: 'website'
    ports:
      - 8080:8080
    depends_on:
      api:
          condition: service_healthy

  nginx:
    image: nginx
    container_name: 'nginx'
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - website
